#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-SQLite2
version:      0.32
version_from: lib/DBD/SQLite2.pm
installdirs:  site
requires:
    DBI:                           1.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
